apiVersion: v1
kind: PersistentVolumeClaim
metadata:
      name: mariadb-pv-claim
      labels:
          type: local
spec:
   storageClassName: manual
   accessModes:
         - ReadWriteOnce
   resources:
         requests:
                storage: 1Gi

