apiVersion: apps/v1
kind: Deployment
metadata:
        name: mariadb-example-secret-configmap
spec:
  replicas: 1
  selector:
      matchLabels:
              app: mariadb
  template:
        metadata:
            labels:
               app: mariadb
        spec: 
         volumes:
             - name: mariadb-data
               persistentVolumeClaim:
                       claimName: mariadb-pv-claim 
         containers:
                 - name: mariadb
                   image: bitnami/mariadb:10.1
                   volumeMounts:
                          - mountPath: /bitnami
                            name: mariadb-data
                   env:
                      - name: ALLOW_EMPTY_PASSWORD
                        valueFrom:
                               secretKeyRef:
                                       name: mariadb-env
                                       key: ALLOW_EMPTY_PASSWORD

                      - name: MARIADB_USER
                        valueFrom:
                               secretKeyRef:
                                       name: mariadb-env
                                       key: MARIADB_USER

                      - name: MARIADB_DATABASE
                        valueFrom:
                               secretKeyRef:
                                       name: mariadb-env
                                       key: MARIADB_DATABASE
