apiVersion: v1
kind: PersistentVolume
metadata:
      name: mariadb-pv
      labels:
          type: local
spec:
   storageClassName: manual
   capacity:
         storage: 1G
   accessModes:
         - ReadWriteOnce
   hostPath: 
        path: "/tmp/mariadb_data"

