apiVersion: v1
kind: Service
metadata:
        name: mariadb-service
        labels:
            run: mariadb-service
spec:
   type: NodePort
   ports:
     - port: 3306
       targetPort: 3306
       protocol: TCP
   selector:
       run : mariadb
